apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-share
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 100Gi

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-csi-premium-share
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-csi-premium
  resources:
    requests:
      storage: 100Gi