apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.rootUsername | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.rootPassword | b64enc }}
