apiVersion: v1
kind: Pod
metadata:
  name: cmvol
spec:
  volumes:
  - name: cmvolmap
    configMap:
      name: test-cm-declarative
  containers:
    - name: cmvol-ctr
      image: nginx
      volumeMounts:
      - name: cmvolmap
        mountPath: /etc/name
