apiVersion: v1
kind: Secret
metadata:
  name: tkb-secret
  labels:
    chapter: configmaps
type: Opaque
data:
  username: dXNlcg==  # base64 encoded "username"
  password: cHJvY2Vzc2Vz  # base64 encoded "password"